version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models   # persist trained models
    restart: always

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
